title: "Sedifex Inventory App Blog"
description: "Sedifex is a modern inventory system in Ghana and Africa for shops, pharmacies, kiosks, and growing businesses."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.sedifex.com" # your custom domain
lang: en
author: "Sedifex Team"
logo: "https://i.imgur.com/mcrrGfd.png"
theme: minima
header_pages:
  - about.md
  - search.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap # generate sitemap.xml
  - jekyll-paginate-v2
future: true
# twitter_username: sedifex
github_username: sedifex

giscus:
  enabled: false
  repo: "owner/repo"
  repo_id: "YOUR_REPO_ID"
  category: "General"
  category_id: "YOUR_CATEGORY_ID"
  theme: light
  lang: en
